[build]
  publish = "docs"
  command = "echo 'Static site ready for deployment'"

[[redirects]]
  from = "/research"
  to = "/Company-Research/index.html"
  status = 200

[[redirects]]
  from = "/research/*"
  to = "/Company-Research/:splat"
  status = 200

[[redirects]]
  from = "/sr-commercial-roofing"
  to = "/Company-Research/sr-commercial-roofing-report.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
